GIOI = {
    0: 'NAM',
    1: 'NU',
}

TINHTHANH = {
    1: 'TP HA NOI',
    8: 'TINH TUYEN QUANG',
    17: 'TINH HOA BINH',
    19: 'TINH THAI NGUYEN',
    22: 'TINH QUANG NINH',
    24: 'TINH BAC GIANG',
    25: 'TINH PHU THO',
    26: 'TINH VINH PHUC',
    27: 'TINH BAC NINH',
    30: 'TINH HAI DUONG',
    31: 'TP HAI PHONG',
    33: 'TINH HUNG YEN',
    34: 'TINH THAI BINH',
    36: 'TINH NAM DINH',
    37: 'TINH NINH BINH',
    35: 'TINH HA NAM',
    38: 'TINH THANH HOA',
    40: 'TINH NGHE AN',
    42: 'TINH HA TINH',
    44: 'TINH QUANG BINH',
    45: 'TINH QUANG TRI',
    46: 'TINH THUA THIEN HUE',
    48: 'TP DA NANG',
    49: 'TINH QUANG NAM',
    51: 'TINH QUANG NGAI',
    52: 'TINH BINH DINH',
    54: "TINH PHU YEN",
    56: "TINH KHANH HOA",
    58: 'TINH NINH THUAN',
    60: "TINH BINH THUAN",
    62: "TINH KON TUM",
    64: 'TINH GIA LAI',
    66: 'TINH DAK LAK',
    67: 'TINH DAK NONG',
    68: "TINH LAM DONG",
    70: "TINH BINH PHUOC",
    72: "TINH TAY NINH",
    74: "TINH BINH DUONG",
    75: "TINH DONG NAI",
    77: "TINH BA RIA - VUNG TAU",
    79: "TP HCM",
    80: "TINH LONG AN",
    82: "TINH TIEN GIANG",
    83: "TINH BEN TRE",
    84: "TINH TRA VINH",
    86: "TINH VINH LONG",
    87: "TINH DONG THAP",
    89: "TINH AN GIANG",
    91: 'TINH KIEN GIANG',
    92: 'TP CAN THO',
    93: 'TINH HAU GIANG',
    94: 'TINH SOC TRANG',
    95: 'TINH BAC LIEU',
    96: 'TINH CA MAU',
}

QUANHUYEN = {
    8: 'QUAN HOANG MAI',
    215: 'HUYEN YEN THE',
    264: 'HUYEN LUONG TAI',
    338: 'HUYEN QUYNH PHU',
    339: 'HUYEN HUNG HA',
    352: 'HUYEN BINH LUC',
    360: 'HUYEN Y YEN',
    361: 'HUYEN NGHIA HUNG',
    397: 'HUYEN TRIEU SON',
    419: 'HUYEN NGHIA DAN',
    430: 'HUYEN NAM DAN',
    506: 'HUYEN DAI LOC',
    528: 'HUYEN TU NGHIA',
    532: 'HUYEN NGHIA HANH',
    540: 'TP QUY NHON',
    545: 'HUYEN PHU MY',
    548: 'HUYEN PHU CAT',
    549: 'HUYEN AN NHON',
    550: 'HUYEN TUY PHUOC',
    555: 'THI XA TUY HOA',
    557: 'HUYEN SONG CAU',
    559: 'HUYEN TUY AN',
    568: 'TP NHA TRANG',
    569: 'THI XA CAM RANH',
    574: 'HUYEN DIEN KHANH',
    582: 'THI XA PHAN RANG - THAP CHAM',
    586: 'HUYEN NINH HAI',
    587: 'HUYEN NINH PHUOC',
    593: 'TP PHAN THIET',
    595: 'HUYEN TUY PHONG',
    599: 'HUYEN TANH LINH',
    600: 'HUYEN DUC LINH',
    608: 'THI XA KON TUM',
    611: 'HUYEN NGOC HOI',
    615: 'HUYEN DAK HA',
    643: 'TP BUON MA THUOT',
    649: 'HUYEN KRONG BUK',
    650: 'HUYEN KRONG NANG',
    654: 'HUYEN KRONG PAC',
    666: 'HUYEN DAK RLAP',
    672: 'TP DA LAT',
    673: 'THI XA BAO LOC',
    678: 'HUYEN DUC TRONG',
    680: 'HUYEN BAO LAM',
    682: 'HUYEN DA TEH',
    689: 'THI XA DONG XOAI',
    691: 'HUYEN PHUOC LONG',
    692: 'HUYEN LOC NINH',
    694: 'HUYEN BINH LONG',
    695: 'HUYEN DONG PHU',
    697: 'HUYEN CHON THANH',
    707: 'HUYEN DUONG MINH CHAU',
    708: 'HUYEN CHAU THANH',
    712: 'HUYEN TRANG BANG',
    718: 'THI XA THU DAU MOT',
    720: 'HUYEN DAU TIENG',
    721: 'HUYEN BEN CAT',
    722: 'HUYEN PHU GIAO',
    723: 'HUYEN TAN UYEN',
    724: 'HUYEN DI AN',
    725: 'HUYEN THUAN AN',
    731: 'TP BIEN HOA',
    732: 'THI XA LONG KHANH',
    734: 'HUYEN TAN PHU',
    735: 'HUYEN VINH CUU',
    736: 'HUYEN DINH QUAN',
    737: 'HUYEN TRANG BOM',
    738: 'HUYEN THONG NHAT',
    739: 'HUYEN CAM MY',
    740: 'HUYEN LONG THANH',
    741: 'HUYEN XUAN LOC',
    742: 'HUYEN NHON TRACH',
    747: 'TP VUNG TAU',
    748: 'THI XA BA RIA',
    750: 'HUYEN CHAU DUC',
    751: 'HUYEN XUYEN MOC',
    752: 'HUYEN LONG DIEN',
    753: 'HUYEN DAT DO',
    754: 'HUYEN TAN THANH',
    755: 'HUYEN CON DAO',
    760: 'QUAN 1',
    761: 'QUAN 12',
    762: 'QUAN THU DUC',
    763: 'QUAN 9',
    764: 'QUAN GO VAP',
    765: 'QUAN BINH THANH',
    766: 'QUAN TAN BINH',
    767: 'QUAN TAN PHU',
    768: 'QUAN PHU NHUAN',
    769: 'QUAN 2',
    770: 'QUAN 3',
    771: 'QUAN 10',
    772: 'QUAN 11',
    773: 'QUAN 4',
    774: 'QUAN 5',
    775: 'QUAN 6',
    776: 'QUAN 8',
    777: 'QUAN BINH TAN',
    778: 'QUAN 7',
    783: 'HUYEN CU CHI',
    784: 'HUYEN HOC MON',
    785: 'HUYEN BINH CHANH',
    786: 'HUYEN NHA BE',
    787: 'HUYEN CAN GIO',
    794: 'THI XA TAN AN',
    799: 'HUYEN TAN TRACH',
    801: 'HUYEN DUC HUE',
    802: 'HUYEN DUC HOA',
    803: 'HUYEN BEN LUC',
    805: 'HUYEN TAN TRU',
    806: 'HUYEN CAN DUOC',
    807: 'HUYEN CAN GIUOC',
    808: 'HUYEN CHAU THANH',
    815: 'TP MY THO',
    816: 'THI XA GO CONG',
    # 817: '',
    818: 'HUYEN TAN PHUOC',
    819: 'HUYEN CAI BE',
    820: 'HUYEN CAI LAY',
    821: 'HUYEN CHAU THANH',
    822: 'HUYEN CHO GAO',
    824: 'HUYEN GO CONG DONG',
    829: 'THI XA BEN TRE',
    831: 'HUYEN CHAU THANH',
    832: 'HUYEN CHO LACH',
    833: 'HUYEN MO CAY',
    835: 'HUYEN BINH DAI',
    836: 'HUYEN BA TRI',
    855: 'THI XA VINH LONG',
    848: 'HUYEN CAU NGANG',
    849: 'HUYEN TRA CU',
    857: 'HUYEN LONG HO',
    859: 'HUYEN VUNG LIEM',
    860: 'HUYEN TAM BINH',
    866: 'THI XA CAO LANH',
    867: 'THI XA SA DEC',
    870: 'HUYEN HONG NGU',
    871: 'HUYEN TAM NONG',
    872: 'HUYEN THAP MUOI',
    873: 'HUYEN CAO LANH',
    876: 'HUYEN LAI VUNG',
    877: 'HUYEN CHAU THANH',
    883: 'TP LONG XUYEN',
    889: 'HUYEN CHAU PHU',
    894: 'HUYEN THOAI SON',
    899: 'THI XA RACH GIA',
    900: 'THI XA HA TIEN',
    908: 'HUYEN AN BIEN',
    918: 'QUAN BINH THUY',
    919: 'QUAN CAI RANG',
    923: 'HUYEN THOT NOT',
    924: 'HUYEN VINH THANH',
    941: 'THI XA SOC TRANG',
    943: 'HUYEN KE SACH',
    954: 'THI XA BAC LIEU',
    957: 'HUYEN PHUOC LONG',
    958: 'HUYEN VINH LOI',
    964: 'TP CA MAU',
    967: 'HUYEN THOI BINH',
    968: 'HUYEN TRAN VAN THOI',
    972: 'HUYEN PHU TAN',
}

TUOITHAI = {
    1: 'DU THANG',
    2: 'THIEU THANG',
    3: 'GIA THANG',
}

PPSINH = {
    1: 'SINH THUONG',
    2: 'SINH MO',
    3: 'SINH HUT',
    4: 'SINH KEM'
}

DTBS = {
    0: 'KHONG',
    1: 'THOAT VI RON',
    2: 'HO HAM ECH',
    99: '',
}

NUOIDUONG6T = {
    1: 'SUA ME',
    2: 'SUA CONG THUC',
    3: 'AN DAM',
    99: '',
}

NHAIMOM = {
    0: 'KHONG',
    1: 'CO',
    98: 'KHONG RO',
}

TCMR = {
    0: 'KHONG',
    1: 'CO',
    98: 'KHONG RO',
}

TANSUATTUAN = {
    0: 'KHONG',
    1: '< 1 LAN/TUAN',
    2: '1 - 3 LAN/TUAN',
    3: '4 - 6 LAN/TUAN',
    4: '> 7 LAN/TUAN ',
}

NHIGIA = {
    0: 'KHONG',
    1: 'CO',
    98: 'KHONG RO'
}

TANSUAT = {
    0: 'KHONG',
    1: 'HIEM KHI',
    2: 'THINH THOANG',
    3: 'THUONG XUYEN',
    4: 'LUON LUON',
}

LAURUAHAUMON = {
    1: 'NUOC',
    2: 'GIAY',
    3: 'XA BONG',
    4: 'XA BONG VA NUOC SAT KHUAN',
    5: 'NUOC MUOI',
    6: 'NGUOI LON RUA',
    99: '',
}

NGUVOI = {
    0: 'KHONG',
    1: 'ONG BA',
    2: 'ANH CHI EM',
    3: 'NGUOI GIU TRE',
    4: 'CO',
    5: 'BAC',
    6: 'ANH CHI EM HO',
    7: 'BAN',
    99: '',
}

DANTOC = {
    1: 'KINH',
    2: 'HOA',
    3: 'MUONG',
    4: 'KHO ME',
    5: 'THO',
}

TONGIAO = {
    0: 'KHONG',
    1: 'PHAT GIAO',
    2: 'THIEN CHUA GIAO',
    3: 'CAO DAI',
    4: 'HOI GIAO',
    5: 'HOA HAO',
    6: 'TIN LANH',
}

NGHENGHIEP = {
    0: 'KHONG',
    1: 'NOI TRO',
    2: 'NONG DAN',
    3: 'CONG NHAN',
    4: 'BUON BAN',
    5: 'NVVP',
    6: 'GIAO VIEN',
    7: 'NVYT',
    8: 'CONG AN, QUAN DOI',
    9: 'TU DO',
    10: 'TAILOR',
    11: 'KINH DOANH',
    12: 'KY SU DIEN',
    13: 'SHIIPER',
    14: 'LAI XE',
    15: 'LAM THUE',
    16: 'THO BAC',
    17: 'MECHANIST',
    18: 'NHAN VIEN KY THUAT',
    19: 'XAY DUNG',
    20: 'QUAN LY',
    21: 'KY SU',
    22: 'THANH TRA GIAO THONG',
    23: 'MAKE UP',
    25: 'DIEN LUC',
    26: 'LUAT SU',
    27: '',
    28: 'CO KHI',
    29: 'THO MOC',
    30: 'THO HO',
    31: 'LAM TOC',
    32: 'NGU DAN',
    33: 'XE OM',
    34: 'BOC XEP',
    35: 'KE TOAN',
    36: 'CHAN NUOI',
    37: 'SUA CHUA DIEN TU',
    38: 'DAU BEP',
    39: 'LAM VUON',
}

TRINHDOHOCVAN = {
    0: 'KHONG DI HOC',
    1: 'BIET DOC VIET',
    2: 'CAP 1',
    3: 'CAP 2',
    4: 'CAP 3',
    5: 'TRUNG CAP NGHE',
    6: 'CAO DANG',
    7: 'DAI HOC',
    8: 'SAU DAI HOC',
}

SONGCHUNG = {
    0: 'KHONG',
    1: 'BA',
    2: 'ME',
    3: 'ONG NOI',
    4: 'BA NOI',
    5: 'ONG NGOAI',
    6: 'BA NGOAI',
    7: 'ANH CHI EM RUOT',
    8: 'NGUOI GIUP VIEC',
    9: 'ONG BA',
    10: 'CAU',
    11: 'DI',
    12: 'CAU DI',
    13: 'CO',
    14: 'CHU',
    15: 'CO CHU',
    16: 'BAC',
    17: 'ANH CHI EM HO',
    18: 'MO',
    19: 'BA DUONG',
    99: '',
}

LOAINHA = {
    1: 'NHA VUON',
    2: 'PHONG TRO',
    3: 'NHA TRO',
    4: 'NHA PHO',
    5: 'CAN HO CHUNG CU',
    6: 'BIET THU',
    7: 'NHA CAP 4',
}

MATTIEN = {
    1: 'QUOC LO',
    2: 'DAI LO',
    3: 'DUONG NHUA XE HOI',
    4: 'DUONG NHUA XE MAY',
    5: 'DUONG NHUA HEM CUT',
    6: 'DUONG DAT',
    7: 'DUONG BE TONG',
    8: 'DUONG TRONG CHUNG CU',
    9: 'DAN NONG THON',
}

LOAINHAVESINH = {
    1: 'BON CAU',
    2: 'BE NGOI XOM',
    3: 'CAU TIEU AO CA',
    4: 'BO',
    99: '',
}

NUOCSINHHOAT = {
    1: 'NUOC MAY',
    2: 'NUOC GIENG KHOAN',
    3: 'NUOC AO HO SONG SUOI',
    4: 'NUOC MUA',
    5: 'NUOC GIENG LOC',
    6: 'CAY NUOC CUA XA',
    99: '',
}

NUOCNAUAN = {
    1: 'NUOC MAY',
    2: 'NUOC GIENG KHOAN',
    3: 'NUOC AO HO SONG SUOI',
    4: 'NUOC MUA',
    5: 'NUOC DONG CHAI',
    6: 'NUOC GIENG LOC',
    7: 'NUOC MAY LOC',
    99: '',
}

NUOCUONG = {
    1: 'NUOC SINH HOAT DUN SOI DE NGUOI',
    2: 'NUOC DONG CHAI',
    3: 'NUOC LOC TRUC TIEP',
    4: 'NUOC MUA',
    5: 'NUOC MAY LOC',
    6: 'NUOC GIENG LOC',
    7: 'NUOC MAY LOC DUN SOI DE NGUOI',
    99: '',
}

VATNUOI = {
    0: 'KHONG',
    1: 'CHO',
    2: 'MEO',
    3: 'GA',
    4: 'VIT',
    5: 'HEO',
    6: 'BO',
    7: 'TRAU',
    8: 'GIA CAM',
    9: 'CA',
    10: 'CHIM',
    11: 'NHIM',
    99: '',

}

TRIEUCHUNG = {
    0: 'KHONG',
    1: 'DAU BUNG',
    2: 'DAU THUONG VI',
    3: 'OI',
    4: 'XHTH TREN',
    5: 'THIEU MAU',
    6: 'CHAN AN',
    7: 'NGAT',
    8: 'NONG RAT SAU XUONG UC',
    9: 'O HOI',
    10: 'NUOT DAU',
    11: 'NUOT KHO',
    12: 'SUT CAN',
    13: 'TRO',
    14: 'BUON NON',
    15: 'DAY HOI',
    16: 'TIEU CHAY',
    17: 'MET',
    18: 'KHO THO',
    19: 'DAU DAU',
    20: 'TIEU PHAN DEN',
    21: 'DANG MIENG',
    22: 'CHONG MAT',
    23: 'NGAT',
    24: 'O CHUA',
    25: 'TIEU MAU DO',
    26: 'TUC NGUC',
    27: 'DAU BUNG MAN',
    28: 'OI MAU',
    29: 'OI TAI DIEN',
    30: 'DAU QUANH RON',
    31: 'XANH XAO',
    32: 'NGUA',
    33: 'AN KEM',
    34: 'SO MUI',
    35: 'NONG',
    36: 'NGHEN',
    37: 'SOT',
    38: 'TAO BON',
    39: 'TANG TIET DAM NHOT',
    40: 'DAU NGUC',
    99: '',

    99: '',
}

THOIDIEMKHOIPHAT = {
    1: 'SANG',
    2: 'TRUA',
    3: 'CHIEU',
    4: 'TOI',
    98: 'KHONG RO',
    99: '',
}

LIENQUANBUAAN = {
    0: 'KHONG',
    1: 'TRUOC',
    2: 'TRONG',
    3: 'SAU',
    98: 'KHONG RO',
    99: '',
}

DAUBUNGVITRI = {
    0: 'THUONG VI',
    1: 'QUANH RON',
    2: 'HA SUON PHAI',
    3: 'HA SUON TRAI',
    4: 'KHAP BUNG',
    5: 'HA VI',
    98: 'KHONG RO',
    99: '',
}

DAUBUNGKIEU = {
    0: 'KHONG',
    1: 'TUNG CON',
    2: 'LIEN TUC',
    3: 'AM I',
    98: 'KHONG RO',
    99: '',
}

DAUBUNGGIAM = {
    1: 'TU HET',
    2: 'NAM NGHI',
    3: 'AN UONG',
    4: 'SAU KHI DI TIEU',
    5: 'TU THE',
    6: 'DUNG THUOC',
    7: 'XOA BUNG',
    8: 'OI',
    9: 'THOA DAU',
    10: 'CHOI VOI ME',
    11: 'CHUOM NONG',
    12: 'KHAM BS',
    13: 'VAT LY TRI LIEU',
    14: 'NAM NGHIENG CO GOI',
    99: ''
}

DAUBUNGANHHUONG = {
    0: 'KHONG',
    1: 'THUC GIAC',
    2: 'NGHI HOC',
    3: 'NGUNG AN UONG',
    4: 'KHONG AN MOT SO MON',
    99: '',
}

OIKIEU = {
    1: 'TUNG CON',
    2: 'LIEN TUC',
    3: 'OI THUC AN',
    4: 'OI DICH VANG XANH',
    5: 'OI KHAN',
    6: 'OI MAU',
    7: 'DICH TRONG, NUOC',
    8: 'DICH NHAY',
    9: 'DICH TRANG',
    98: 'KHONG RO',
    99: '',
}

OICAMGIAC = {
    1: 'DE CHIU',
    2: 'KHO CHIU',
    98: 'KHONG RO',
    99: '',
}

THAYDOICANNANG = {
    98: 'TANG KHONG RO',
    -98: 'GIAM KHONG RO',
    98.0: 'TANG KHONG RO',
    -98.0: 'GIAM KHONG RO',
}

NHOMMAU = {
    1: 'A',
    2: 'B',
    3: 'AB',
    4: 'O',
    98: 'KHONG RO',
}

XETNGHIEM = {
    0: 'KHONG',
    1: 'PHAN',
    2: 'HOI THO',
    3: 'MAU',
    4: 'NOI SOI',
    98: 'KHONG RO',
    99: '',
}

THUOC = {
    1000: 'KHONG RO',
    1100: 'KHANG SINH',
    1101: 'AMOXICILLIN',
    1301: 'CLARITHROMYCIN',
    1401: 'LEVOFLOXACIN',
    1501: 'METRONIDAZOLE',
    1502: 'IMIDAZOLE',
    3100: 'PPIS',
    3101: 'ESOMEPRAZOLE',
    3102: 'OMEPRAZOLE',
    3103: 'RABEPRAZOLE',
    3104: 'PANTOPRAZOLE',
    3105: 'LANSOPRAZOLE',
    3301: 'ALUMINIUM PHOSPHATE',
    3501: 'RANITIDIN',
    3601: 'BISMUTH',
    3602: 'SUCRALFAT',
    3604: 'SIMETHICONE',
    3605: 'LACTULOSE',
    99: '',
}

NGUOITHAN = {
    0: 'KHONG',
    1: 'BA',
    2: 'ME',
    3: 'ONG NOI',
    4: 'BA NOI',
    5: 'ONG NGOAI',
    6: 'BA NGOAI',
    7: 'ACE RUOT',
    8: 'NGUOI GIUP VIEC',
    9: 'BAN THAN BE',
    10: 'BAC',
    11: 'CHU',
    12: 'ONG CO',
    13: 'CO',
    14: 'CAU',
    15: 'ACE HO',
    16: 'DI',
    17: 'MO',
    18: 'ONG CHU',
    98: 'KHONG RO',
    99: ''
}

TONTHUONG = {
    0: 'BINH THUONG',
    1: 'TRAO NGUOC',
    2: 'VIEM SUNG HUYET',
    3: 'VIEM XUAT HUYET',
    4: 'VIEM TROT NONG',
    5: 'VIET TROT NOI',
    6: 'VIEM TEO NIEM MAC',
    7: 'VIEM PHU NE',
    8: 'VIEM DANG NOT',
    9: 'LOET',
    10: 'NAM',
    11: 'VAI O LOET NONG',
    12: 'VIEM TRAO NGUOC GRADE A',
    13: 'GIA MAC',
    14: 'SUNG HUYET',
    15: 'CO KEO',
    16: 'POLYP',
    17: 'VIEM XUAT TIET',
    18: 'KHOI THAY DOI BE MAT NIEM MAC',
    98: 'KHONG RO',
    99: '',
}

FOREST = {
    1: 'IA',
    2: 'IB',
    3: 'IIA',
    4: 'IIB',
    5: 'IIC',
    6: 'III',
}

TINHCHATDICH = {
    1: 'THUC AN',
    2: 'DICH VANG XANH',
    3: 'KHAN',
    4: 'MAU',
    5: 'DICH NHAY',
    6: 'DOM',
    7: 'NUOC DICH TRONG',
    98: 'KHONG RO',
    99: '',
}

GPBVITRI = {
    1: 'HANG VI',
    2: 'THAN VI',
    3: 'HANG THAN VI',
    4: '2 VI TRI'
}

GPBMUCDO = {
    0: 'KHONG',
    1: 'NHE',
    2: 'TRUNG BINH',
    3: 'NANG',
    4: 'CO NHUNG KHONG RO MUC DO',
    98: 'KHONG RO',
}

TONTHUONGGPB = {
    0: 'KHONG',
    1: 'NANG LYMPHO',
    2: 'CO TUONG BAO',
    3: 'TANG SAN SOI',
    4: 'XO HOA',
    5: 'NANG LYMPHO DUOI NIEM',
    6: 'EOSINOPHILLIC',
    99: '',
}

UONGTHUOC = {
    0: 'KHONG',
    1: 'TRUOC AN 30P',
    2: 'TRONG KHI AN',
    3: 'SAU AN',
    4: 'BAT CU KHI NAO THUAN TIEN',
    5: 'TRUOC AN 15P',
    6: 'TRUOC AN 60P',
}

BENH = {
    1: 'K DA DAY',
    2: 'VIEM DA DAY',
    3: 'VIEM TA TRANG',
    4: 'LOET DA DAY',
    5: 'LOET TA TRANG',
    6: 'NHIEM HP',
    7: 'TANG HUYET AP',
    8: 'DAI THAO DUONG',
    9: 'HEN',
    10: 'TIEU CHAY NHIEM TRUNG',
    11: 'BACH CAU CAP',
    12: 'SOT XUAT HUYET',
    13: 'VIEM AMIDAN',
    14: 'DI UNG',
    15: 'GERD',
    16: 'THALASSEMIE',
    17: 'VIEM BANG QUANG',
    18: 'ADHD',
    19: 'NHIEM TRUNG TIEU HOA',
    20: 'VIEM MUI DI UNG',
    21: 'VIEM PHOI',
    22: 'VIEM GAN',
    23: 'NANG BUONG TRUNG',
    24: 'XUAT HUYET TIEU HOA',
    25: 'DI UNG THUC AN',
    26: 'NHIEM TRUNG HUYET',
    27: 'XUAT HUYET AMIDAN',
    28: 'GAN NHIEM MO',
    29: 'TIEU CHAY CAP',
    30: 'SUY HO HAP',
    31: 'VIEM XEP PHOI',
    32: 'ASD',
    33: 'XUAT HUYET GIAM TEIU CAU VO CAN',
    34: 'SANH NON',
    35: 'NHE CAN',
    36: 'VIEM GAN B',
    37: 'K DAI TRANG',
    38: 'CHAY MAU CAM',
    39: 'ROI LOAN TIEU HOA',
    40: 'VIEM TIEU PHE QUAN',
    41: 'VIEM HONG',
    42: 'U LO CHAM',
    43: 'VIEM XOANG',
    44: 'TRI',
    45: 'VIEM DA CO DIA',
    46: 'VIEM TIEU PHE QUAN',
    47: 'VIEM XOANG',
    48: 'VIEM TAI MAN',
    49: 'BENH THAN MAN',
    50: 'ROI LOAN TIEN DINH',
    51: 'THUNG DA DAY',
    52: 'SOI THAN',
    53: 'THAN U NUOC',
    54: 'DAY THI SOM',
    55: 'DAP CHAN',
    56: 'VIEM RUOT THUA',
    57: 'THIEU MAU THIEU SAT',
    58: 'CAT AMIDAN',
    59: 'SOI MAT',
    60: 'KAWASAKI',
    61: 'VIEM TAI GIUA',
    62: 'VIEM DAI TRANG',
    63: 'LONG RUOT',
    64: 'TU KY',
    65: 'VIEM KHOP THIEU NIEN',
    66: 'THOAT VI BEN',
    67: 'GAY XUONG',
    68: 'VAY NEN',
    69: 'TAY CHAN MIENG',
    70: 'LAO',
    71: 'NANG ONG MAT CHU',
    72: 'TRAN DICH MANG PHOI',
}

CAY = {
    0: 'KHONG',
    1: 'CO',
    2: 'VK THOAI TRIEN',
    98: 'KHONG RO'
}
