import pandas as pd
import path
import F2Z_helper as F2Z
import F2A_helper as F2A
import F2B_helper as F2B
import F2C_helper as F2C
import F2D_helper as F2D
import F2E_helper as F2E
import F2F_helper as F2F
import F2G_helper as F2G
import F2H_helper as F2H
import F3A_helper as F3A
import F3B_helper as F3B
import F3E_helper as F3E
import F3F_helper as F3F
import F3G_helper as F3G
import F4A_helper as F4A
import F4C_helper as F4C
import F52A_helper as F52A
import F52C_helper as F52C
import F52D_helper as F52D

def main():
    print("Execute pipeline 1")
    df = (F2Z.NGAY()
        .merge(F2Z.MAHS(), how='left')
        .merge(F2Z.F2Z1(), how='left')
        .merge(F2Z.F2Z2(), how='left')
        .merge(F2Z.F2Z3(), how='left')
        .merge(F2Z.F2Z4_1(), how='left')
        .merge(F2Z.F2Z4_2(), how='left')
        .merge(F2Z.F2Z5_1(), how='left')
        .merge(F2Z.F2Z5_2(), how='left')
        .merge(F2A.F2A1(), how='left')
        .merge(F2A.F2A2(), how='left')
        .merge(F2A.F2A3(), how='left')
        .merge(F2A.F2A4(), how='left')
        .merge(F2A.F2A5(), how='left')
        .merge(F2A.F2A6(), how='left')
        .merge(F2A.F2A7(), how='left')
        .merge(F2A.F2A8(), how='left')
        .merge(F2A.F2A9(), how='left')
        .merge(F2A.F2A10(), how='left')
        .merge(F2A.F2A11(), how='left')
        .merge(F2B.F2B1_F2B11(), how='left')
        .merge(F2B.F2B12_F2B15(), how='left')
        .merge(F2C.F2C1_F2C52(), how='left')
        .merge(F2C.F2C53(), how='left')
        .merge(F2D.F2D1_F2D7(), how='left')
        .merge(F2D.F2D8(), how='left')
        .merge(F2E.F2E1(), how='left')
        .merge(F2E.F2E2(), how='left')
        .merge(F2E.F2E3(), how='left')
        .merge(F2E.F2E4(), how='left')
        .merge(F2F.F2F2(), how='left')
        .merge(F2F.F2F3_F2F7(), how='left')
        .merge(F2G.F2G1(), how='left')
        .merge(F2G.F2G2_F2G4(), how='left')
        .merge(F2G.F2G5_F2G7(), how='left')
        .merge(F2G.F2G8_F2G9(), how='left')
        .merge(F2G.F2G10_F2G11(), how='left')
        .merge(F2G.F2G12_F2G13(), how='left')
        .merge(F2G.F2G14_F2G15(), how='left')
        .merge(F2G.F2G16A_F2G16B(), how='left')
        .merge(F2G.F2G17(), how='left')
        .merge(F2H.F2H1A(), how='left')
        .merge(F2H.F2H1B(), how='left')
        .merge(F2H.F2H2(), how='left')
        .merge(F2H.F2H3(), how='left')
        .merge(F2H.F2H4(), how='left')
        .merge(F2H.F2H5(), how='left')
        .merge(F2H.F2H6(), how='left')
        .merge(F2H.F2H7(), how='left')
        .merge(F2H.F2H8_KHONGPHONG(), how='left')
        .merge(F2H.F2H8_PHONGKHACH(), how='left')
        .merge(F2H.F2H8_PHONGNGU(), how='left')
        .merge(F2H.F2H8_NHABEP(), how='left')
        .merge(F2H.F2H8_NHAVSNHATAM(), how='left')
        .merge(F2H.F2H8_NHATAMRIENG(), how='left')
        .merge(F2H.F2H8_NHAVSRIENG(), how='left')
        .merge(F2H.F2H8_NHAKHO(), how='left')
        .merge(F2H.F2H8_NHAXE(), how='left')
        .merge(F2H.F2H8_PHONGHOC(), how='left')
        .merge(F2H.F2H9(), how='left')
        .merge(F2H.F2H10(), how='left')
        .merge(F2H.F2H11(), how='left')
        .merge(F2H.F2H12(), how='left')
        .merge(F2H.F2H13(), how='left')
        .merge(F2H.F2H14(), how='left')
        .merge(F2H.F2H15(), how='left')
        .merge(F2H.F2H16(), how='left')
        .merge(F2H.F2H17(), how='left')
        .merge(F2H.F2H18(), how='left')
    )
    df = (df
    .merge(F3A.F3A1(), how='left')
        .merge(F3A.F3A2(), how='left')
        .merge(F3A.F3A3(), how='left')
        .merge(F3A.F3A4(), how='left')
        .merge(F3A.F3A4A(), how='left')
        .merge(F3A.F3A4B(), how='left')
        .merge(F3A.F3A4C(), how='left')
        .merge(F3A.F3A4D(), how='left')
        .merge(F3A.F3A4E(), how='left')
        .merge(F3A.F3A4F(), how='left')
        .merge(F3A.F3A4G(), how='left')
        .merge(F3A.F3A5(), how='left')
        .merge(F3A.F3A5A(), how='left')
        .merge(F3A.F3A5B(), how='left')
        .merge(F3A.F3A5C(), how='left')
        .merge(F3A.F3A5D(), how='left')
        .merge(F3A.F3A5E(), how='left')
        .merge(F3A.F3A6A(), how='left')
        .merge(F3A.F3A6B(), how='left')
        .merge(F3A.F3A7(), how='left')
        .merge(F3A.F3A8(), how='left')
        .merge(F3A.F3A9(), how='left')
        .merge(F3A.F3A9A(), how='left')
        .merge(F3A.F3A10(), how='left')
        .merge(F3B.F3B1(), how='left')
        .merge(F3B.F3B1A(), how='left')
        .merge(F3B.F3B1B(), how='left')
        .merge(F3B.F3B2(), how='left')
        .merge(F3B.F3B2A(), how='left')
        .merge(F3B.F3B2B(), how='left')
        .merge(F3B.F3B2C(), how='left')
        .merge(F3B.F3B2D(), how='left')
        .merge(F3B.F3B2E(), how='left')
        .merge(F3B.F3B2F(), how='left')
        .merge(F3B.F3B3(), how='left')
        .merge(F3E.F3E1A(), how='left')
        .merge(F3E.F3E1B(), how='left')
        .merge(F3E.F3E1C(), how='left')
        .merge(F3E.F3E1D(), how='left')
        .merge(F3E.F3E1E(), how='left')
        .merge(F3E.F3E2A(), how='left')
        .merge(F3E.F3E2B(), how='left')
        .merge(F3E.F3E3(), how='left')
        .merge(F3F.F3F1(), how='left')
        .merge(F3F.F3F2(), how='left')
        .merge(F3G.F3G1_F3G4(), how='left')
        .merge(F3G.F3G6(), how='left')  # TODO
        .merge(F3G.F3G7_PV(), how='left')
        .merge(F3G.F3G7_TV(), how='left')
        .merge(F3G.F3G7_HV(), how='left')
        .merge(F3G.F3G7_MV(), how='left')
        .merge(F3G.F3G7_HTT(), how='left')
        .merge(F3G.F3G7_D2(), how='left')
        .merge(F3G.F3G8_PV(), how='left')
        .merge(F3G.F3G8_TV(), how='left')
        .merge(F3G.F3G8_MV(), how='left')
        .merge(F3G.F3G8_HV(), how='left')
        .merge(F3G.F3G8_HTT(), how='left')
        .merge(F3G.F3G8_D2(), how='left')
    )

    df = (df
        .merge(F4A.F4A1(), how='left')
        .merge(F4A.F4A1A(), how='left')
        .merge(F4A.F4A2(), how='left')
        .merge(F4A.F4A2A(), how='left')
        .merge(F4A.F4A3A(), how='left')
        .merge(F4A.F4A3B(), how='left')
        .merge(F4A.F4A4(), how='left')
        .merge(F4A.F4A5(), how='left')
        .merge(F4A.F4A7(), how='left')
        .merge(F4A.F4A8(), how='left')
        .merge(F4C.F4C1(), how='left')
        .merge(F4C.F4C2(), how='left')
        .merge(F4C.F4C3(), how='left')
        .merge(F4C.F4C4(), how='left')
        .merge(F4C.F4C4_HV(), how='left')
        .merge(F4C.F4C4_HVTT(), how='left')
        .merge(F4C.F4C4_TV(), how='left')
        .merge(F4C.F4C4_TVTT(), how='left')
        .merge(F4C.F4C4_HTV(), how='left')
        .merge(F4C.F4C4_HTVTT(), how='left')
    )
    df = (df
        .merge(F52A.F52A1(), how='left')
        .merge(F52A.F52A1A(), how='left')
        .merge(F52A.F52A2(), how='left')
        .merge(F52A.F52A2A(), how='left')
        .merge(F52A.F52A3A(), how='left')
        .merge(F52A.F52A3B(), how='left')
        .merge(F52A.F52A4(), how='left')
        .merge(F52A.F52A5(), how='left')
        .merge(F52A.F52A8(), how='left')
        .merge(F52A.F52A9(), how='left')
        .merge(F52C.F52C1(), how='left')
        .merge(F52C.F52C1A_LAN1_GIO(), how='left')
        .merge(F52C.F52C1A_LAN1_PHUT(), how='left')
        .merge(F52C.F52C1A_LAN2_GIO(), how='left')
        .merge(F52C.F52C1A_LAN2_PHUT(), how='left')
        .merge(F52C.F52C2(), how='left')
        .merge(F52C.F52C2A_LAN1_GIO(), how='left')
        .merge(F52C.F52C2A_LAN1_PHUT(), how='left')
        .merge(F52C.F52C2A_LAN2_GIO(), how='left')
        .merge(F52C.F52C2A_LAN2_PHUT(), how='left')
        .merge(F52C.F52C4_F52C5(), how='left')
        .merge(F52D.F52D1_F52D7(), how='left')
        .merge(F52D.F52D8(), how='left')
    )
    # view sample
    cols = [0] + list(range(295, 300))
    # print(df.iloc[:, cols].info())
    print(df.iloc[:, cols].sample(5))
    print(df.shape)
    # print(df.query('F2A5 != "KHONG"'))
    # print(df[df['F2A11'] == 'KHONG RO'])
    df.to_excel(path.OUTPUT_MAIN)


# def main1():
#     df = (F2Z.NGAY()
#         .merge(F2Z.MAHS(), how='left')
#     )
#     print(df.shape)

if __name__ == "__main__":
    main()
