ENTRY = '../../data/external/prd_v2.0.0_Entry.csv'
HANHCHINH = '../../data/external/prd_v2.0.0_HanhChinh.csv'
FORM2 = '../../data/external/prd_v2.0.0_Form2.csv'
FORM3 = '../../data/external/prd_v2.0.0_Form3.csv'
CTM = '../../data/external/prd_v2.0.0_CTM.csv'
NS = '../../data/external/prd_v2.0.0_NoiSoi.csv'
TK = '../../data/external/prd_v2.0.0_TaiKham.csv'
CAY = '../../data/external/prd_v2.0.0_Cay.csv'
PCR = '../../data/external/prd_v2.0.0_PCR.csv'
GPB = '../../data/external/prd_v2.0.0_GPB.csv'
TDP = '../../data/external/prd_v2.0.0_TacDungPhu.csv'
TIENCAN = '../../data/external/prd_v2.0.0_TienCan.csv'

OUTPUT_MAIN = '../../data/intermediate/main.xlsx'
INTERMEDIATE = '../../data/intermediate/'